language: python

env:
 - DJANGO_VERSION=2.2
 - DJANGO_VERSION=3.0
 - DJANGO_VERSION=master

python:
 - "3.5"
 - "3.6"
 - "3.7"
 - "3.8"

matrix:
  exclude:
    - python: "3.5"
      env: DJANGO_VERSION=3.0
    - python: "3.5"
      env: DJANGO_VERSION=master

install:
 - if [[ $DJANGO_VERSION != master ]]; then pip install --pre -q "Django>=${DJANGO_VERSION},<${DJANGO_VERSION}.99"; fi
 - if [[ $DJANGO_VERSION == master ]]; then pip install https://github.com/django/django/archive/master.tar.gz; fi

script:
 - python runtests.py
